version: '3.4'

services:
    db:
      image: postgres:14.6
      restart: always
      environment:
        - POSTGRES_USER=userpostgres
        - POSTGRES_PASSWORD=passwordpostgres
      

      ports:
        - 5432:5432

