
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= Rails.application.credentials.db_password %>

development:
  <<: *default
  database: blog_dev
  username: <%= ENV["DATABASE_USER"] %>
  host: <%= ENV["DATABASE_HOST"] %>
 
test:
  <<: *default
  database: blog_test
  username: <%= ENV["DATABASE_USER"] %>
  host: <%= ENV["DATABASE_HOST"] %>

production:
  <<: *default
  database: blog_prod
  username: <%= ENV["DATABASE_USER"] %>
  host: <%= ENV["DATABASE_HOST"] %>
